config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "clinics", to: "clinics#index"
  get "clinics/search", to: "clinics#search"

  get "emergency", to: "emergency#index", as: :emergency

  resources :chats, only: [:index, :create, :show] do
    resources :messages, only: [:create]
  end
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  # validates if the chatbot sent an initial message

  DEFAULT_TITLE = ""
  TITLE_PROMPT = "Generate a short, descriptive, 3-to-6 word title that summarizes the user question for a chat conversation."
  SYMPTOM_PROMPT = "Generate a concise list of symptoms mentioned by the user in the conversation. and return as json"

  def generate_title_from_first_message
    return unless title == DEFAULT_TITLE

    first_user_message = messages.where(role: "user").order(:created_at).first
    return if first_user_message.nil?

    response = RubyLLM.chat(provider: :openai, assume_model_exists: true).with_instructions(TITLE_PROMPT).ask(first_user_message.content)
    update(title: response.content)
  end

  def generate_symptom_from_conversation
    return unless respond_to?(:symptom) && symptom.blank?
    first_user_message = messages.where(role: "user").order(:created_at).first
    return if first_user_message.nil?
    response = RubyLLM.chat(provider: :openai, assume_model_exists: true).with_instructions(SYMPTOM_PROMPT).ask(first_user_message.content)
    update(symptom: response.content)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
    @chat = Chat.new
    @chats = current_user.chats.all
  end

  def create
    @chat = Chat.new(params[:id])
    @chat.title = Chat::DEFAULT_TITLE
    @chat.user = current_user
    if @chat.save
      redirect_to chat_path(@chat)
    else
      redirect_to root_path, flash: { notice: "Failed to create a chat! Make sure you are logged in!"}
    end
  end

  def show
    @chat = current_user.chats.find(params[:id])
    @message = Message.new
  end
end

app/views/chats/index.html.erb
<div class="container mt-5">
  <div class="cards mb-5">
    <%= simple_form_for @chat do |f| %>
      <button type="submit" class="card-submit-btn">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
          <i class="bi bi-prescription2"></i>
          <span>Find Me Drugs</span>
        </div>
      </button>
    <% end %>
    <%= link_to clinics_path, class: "card-link", aria: { label: "Find a clinic near me" } do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
        <i class="bi bi-map"></i>
        <span> Find Me A Clinic</span>
      </div>
    <% end %>
    <%= link_to emergency_path, class: "card-link", aria: { label: "Emergency information" } do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
        <i class="bi bi-exclamation-triangle"></i>
        <span>Emergency</span>
      </div>
    <% end %>
  </div>
  <hr>
  <h3>My Chats</h3>
  <ul class="list-unstyled">
    <% @chats.each do |chat| %>
      <% if chat.messages.present? %>
        <li class="list-item">
          <%= link_to chat.title, chat_path(chat), class: "btn btn-outline-secondary my-1 w-100 text-start" %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/chats/show.html.erb
<div class="m-3">
  <h2>
    <%= @chat.title %>
  </h2>
</div>
<div class="container">
  <div class="container">
    <% if @chat.messages === nil %>
      <p>
        You don't have any messages yet! Start chatting with mAiku to see some messages!
      </p>
    <% else %>
      <% @chat.messages.each do |message| %>
        <% if message.role == "user" %>
          <div class="d-flex justify-content-end mb-2">
            <div class="bg-white px-3 pt-2 rounded-4 chat-bubble-content shadow-sm">
              <%= raw(render_markdown(message.content)) %>
            </div>
          </div>
        <% elsif message.role == "assistant" %>
          <div class="d-flex justify-content-start mb-4">
            <div class="bg-light px-3 py-2 rounded-4 chat-bubble-content shadow-sm">
              <%= raw(render_markdown(message.content))%>
              Some recommended drugs are:
              <div class="container row gap-4">
                <% message.drugs.each do |drug| %>
                  <div class="card col align-items-center p-1 rounded-4" style="background-color: white;">
                    <img src=<%= drug.image_url %> alt="image of the drug", style="background-color: white; width: 200px; height: 200px;">
                    <div>
                      <strong><%= drug.name %></strong>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="container sticky-bottom bg-light p-3">
    <%= simple_form_for [@chat, @message] do |f| %>
      <%= f.input :content, label: "Ask me something?", required: true, placeholder: "What is the best drug for me?" %>
      <%= f.button :submit, "Ask Mai-kun", class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>